# Generated by Django 2.2.28 on 2023-07-06 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xvfbf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vnnfj', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sdfv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bvfdn', models.BigIntegerField()),
                ('tryry', models.BigIntegerField()),
                ('ourye', models.BigIntegerField()),
                ('rel_xvfbf_1_1', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sdfv_rel_xvfbf_1_1', to='home.Xvfbf')),
            ],
        ),
    ]
